version: 2
sources:
  - name: source
    tables: 
      - name: benefits
      - name: departments
      - name: employee_benefits
      - name: employee_salaries
      - name: employees
      - name: payroll
      - name: timesheet
      