version: 2

models:
  - name: annual_completed_housing
    description: |
      Data transformations for census completed housing units
    columns:
      - name: uuid
        description: "The primary key for this table"
        data_tests:
          - unique
          - not_null
      - name: created_ts
      - name: year
      - name: single_family_total
      - name: single_family_built_for_sale
      - name: single_family_fee_simple
      - name: single_family_contractor_built
      - name: single_family_owner_built
      - name: multi_family_total
      - name: multi_family_for_sale
      - name: multi_family_for_rent
      - name: multi_family_2_to_4_units
      - name: multi_family_5_to_9_units
      - name: multi_family_10_to_19_units
      - name: multi_family_20_or_more_units
  - name: annual_started_housing
    description: |
      Data transformations for census started housing units
    columns:
      - name: uuid
        description: "The primary key for this table"
        data_tests:
          - unique
          - not_null
      - name: created_ts
      - name: year
      - name: single_family_total
      - name: single_family_built_for_sale
      - name: single_family_fee_simple
      - name: single_family_contractor_built
      - name: single_family_owner_built
      - name: multi_family_total
      - name: multi_family_for_sale
      - name: multi_family_for_rent
      - name: multi_family_2_to_4_units
      - name: multi_family_5_to_9_units
      - name: multi_family_10_to_19_units
      - name: multi_family_20_or_more_units